### PR TITLE
add images to OLED

### PR DESCRIPTION
**Pull request by NoSloppy**

### CODE REVIEW

**Comment by profezzorn** [comment]
This is going to have to wait until 7.x
I don't want to check it in right now, because there are still issues to be worked out in 6.x.

**Comment by NoSloppy** [comment]
Understood. Just wanted to get it up for casual review.

**Comment by NoSloppy** [comment]
testing comment

**Comment by profezzorn** [comment]
Looks like this has conflicts now.

**Comment by NoSloppy** [comment]
Closing and resubmitting to resolve confilcts

**Pull request closed without merging**
