### PR TITLE
add easy preon check

### PR DESCRIPTION
**Pull request by NoSloppy**
Sometimes just checking if (!SaberBase::IsOn()) doesn't cut it.

### CODE REVIEW

**Comment by profezzorn** [comment]
What about just using IsOn() ?

**Comment by NoSloppy** [comment]
In the use case I have where blades are turned on or off with a toggle, IsOn() is wrong in one of the 2 states. It's not a good check, so I was hoping this small addition to hybrid_font would be ok.
In addition, it makes all the "prevent during preon" checks throughout the prop more readable without needing a comment explaining why we're checking IsOn()

**Comment by profezzorn** [comment]
I'm still a bit confused.

First of all: It's not clear to me if you need a way to tell the difference between "preon" and "on or preon".
Second: There is a function in prop_base called IsOn which return "on or preon", it is called IsOn() is that not what you need?
Third: If that is not what you need, there is also a variable called on_pending_ which is true during preon, why not just use that?

**Comment by NoSloppy** [comment]
Ah look at that.
I hadn't realized on_pending_ would be in scope. Works perfectly, thanks. Closing this.

**Pull request closed without merging**
