### PR TITLE
add quote

### PR DESCRIPTION
**Pull request by NoSloppy**
Time to make this official yet?
Saberbase supports the blade effect.

### CODE REVIEW

**Comment by profezzorn** [comment]
We'll also need some support in hybrid_font.h then.

**Comment by NoSloppy** [comment]
> We'll also need some support in hybrid_font.h then.

oh?
Not sure in what capacity you mean.
Props handle calling it...

**Comment by profezzorn** [comment]
If props handle playing the effect, then they should also declare the effect.

If we're going to have a global EFFECT(quote) then I think hybrid font ought to have a:

   case EFFECT_QUOTE: PlayCommon(&SFX_quote); 

or something similar as well.

**Comment by NoSloppy** [comment]
> : PlayCommon(&SFX_quote);

Ah yes, forgot this was handled in the prop in SB_Effect override.
How about now?

**Pull request merged**
