### PR TITLE
"Font directory" spoken as "font folder" instead

### PR DESCRIPTION
**Pull request by NoSloppy**
Not sure if you're into this, but it seems most average users don't call it a directory, and/or have difficulty understanding the talkie.
Completely doesn't matter, but maybe?
The rest of the code still uses talkie_font_directory_15.

### CODE REVIEW

**Comment by profezzorn** [comment]
How does this actually sound?

**Comment by NoSloppy** [comment]
> How does this actually sound?


https://user-images.githubusercontent.com/53964195/116773623-6b428c00-aa24-11eb-8542-f0cdf5845dcb.mov

**Comment by NoSloppy** [comment]
Like that

**Comment by profezzorn** [comment]
Hmm, I'm not sure I like it, "font folder" just doesn't sound as accurate as "font directory" to me.
Also, it takes more space.

**Pull request closed without merging**
