### PR TITLE
add sample_OS6_config

### PR DESCRIPTION
**Pull request by NoSloppy**

### CODE REVIEW

**Comment by NoSloppy** [comment]
I just saw that fett263 provides one similar through his site. Maybe this should get some stuff from that, or vice-versa.

**Comment by profezzorn** [comment]
I'm wondering if this file needs a better name?
Also, I'm trying to make it so that fett263 can be a part of the code review for this file...

**Comment by fdarosa2663** [comment]
It's probably better if I just submit the one I have linked from the library it's more up to date and has all of the recommended defines tied to my prop.  I'll get it submitted later this week once I get a chance.

**Comment by profezzorn** [comment]
I'm going to keep this code review open for now, and when we get the other one submitted, we can compare and see if there are some parts of this one that should be copied over.

**Comment by NoSloppy** [comment]
I think this is done now.

**Pull request closed without merging**
