### PR TITLE
Option to limit Low Batt notification to only play once

### PR DESCRIPTION
**Pull request by NoSloppy**
Tried to do this in prop file and not edit a system file, but doesn't seem easily done, if even possible.

### CODE REVIEW

**Comment by profezzorn** [comment]
Isn't it just a matter of overriding CheckLowBattery() ?

**Comment by NoSloppy** [comment]
But this lets the saber still turn off if low.

**Comment by profezzorn** [comment]
You don't have to override CheckLowBattery() with one that does nothing though.

**Comment by profezzorn** [comment]
Still think this can be done by overriding CheckLowBattery().

**Pull request closed without merging**
