### PR TITLE
fix issue with multiple blade detection on ignition when blade is in

### PR DESCRIPTION
**Pull request by ishtob**

### CODE REVIEW

**Comment by profezzorn** [comment]
Seems ok, but I'm not sure why this fixes anything?
Can you explain?

**Comment by ishtob** [comment]
unsure either, but now not getting blade change trigger when the blade is plugged in while the blade is on, though serial is putting out Select_ON / Select_OFF (btw, think this naming should be changed for the debug readout)

**Comment by ishtob** [comment]
so reverted the change, started playing with the time floating, and setting it to 100 seems to fix tne problem without loosing the detection triggering while blade is on

**Comment by ishtob** [comment]
vote for floating latch implemented, making this PR outdated. closing

**Pull request closed without merging**
